package app.codeforge.mobile.ui.theme

import androidx.compose.ui.graphics.Color

data class CodeForgeMobileTheme(
    val id: String,
    val label: String,
    val mood: String,
    val background: List<Color>,
    val sidebar: List<Color>,
    val surface: Color,
    val surfaceStrong: Color,
    val text: Color,
    val mutedText: Color,
    val accent: Color,
    val border: Color,
    val isDark: Boolean
)

val CodeForgeMobileThemes = listOf(
    CodeForgeMobileTheme(
        id = "modern-dark",
        label = "Modern Dark",
        mood = "Ruhig und kompakt",
        background = listOf(Color(0xFF1C181A), Color(0xFF111111), Color(0xFF0A0A0A)),
        sidebar = listOf(Color(0xFF251F21), Color(0xFF0A0A0A)),
        surface = Color(0xFF181416),
        surfaceStrong = Color(0xFF242124),
        text = Color(0xFFE4E4E7),
        mutedText = Color(0xFFA1A1AA),
        accent = Color(0xFFF2C96D),
        border = Color.White.copy(alpha = 0.10f),
        isDark = true
    ),
    CodeForgeMobileTheme(
        id = "classic-light",
        label = "Classic Light",
        mood = "Hell und sachlich",
        background = listOf(Color(0xFFF5F2ED), Color(0xFFE5E1D8), Color(0xFFD1CCC0)),
        sidebar = listOf(Color(0xFFF2EEE7), Color(0xFFD8D1C5)),
        surface = Color(0xF2FFFFFF),
        surfaceStrong = Color(0xFFF5F1EA),
        text = Color(0xFF18181B),
        mutedText = Color(0xFF52525B),
        accent = Color(0xFF7C5A1F),
        border = Color.Black.copy(alpha = 0.10f),
        isDark = false
    ),
    CodeForgeMobileTheme(
        id = "deep-galactic",
        label = "Deep Galactic",
        mood = "Tief, blau, fokussiert",
        background = listOf(Color(0xFF0E121D), Color(0xFF05060A), Color(0xFF020202)),
        sidebar = listOf(Color(0xFF151A2A), Color(0xFF05060A)),
        surface = Color(0xFF141827),
        surfaceStrong = Color(0xFF20263A),
        text = Color(0xFFE4E4E7),
        mutedText = Color(0xFFA1A1AA),
        accent = Color(0xFF64D2FF),
        border = Color.White.copy(alpha = 0.09f),
        isDark = true
    ),
    CodeForgeMobileTheme(
        id = "muted-earth",
        label = "Muted Earth",
        mood = "Warm und weich",
        background = listOf(Color(0xFFE5E1D8), Color(0xFFD1CCC0), Color(0xFFC4C0B4)),
        sidebar = listOf(Color(0xFFEDE8DF), Color(0xFFCFC7B8)),
        surface = Color(0xEFFFFFFF),
        surfaceStrong = Color(0xFFEDE8DF),
        text = Color(0xFF27211A),
        mutedText = Color(0xFF6F5F46),
        accent = Color(0xFF8A6F3D),
        border = Color.Black.copy(alpha = 0.10f),
        isDark = false
    ),
    CodeForgeMobileTheme(
        id = "neon-cyber",
        label = "Neon Cyber",
        mood = "Kontrastreich",
        background = listOf(Color(0xFF1A1A1A), Color(0xFF0A0A0A), Color(0xFF050505)),
        sidebar = listOf(Color(0xFF202026), Color(0xFF060606)),
        surface = Color(0xFF151518),
        surfaceStrong = Color(0xFF23232A),
        text = Color(0xFFE4E4E7),
        mutedText = Color(0xFFA1A1AA),
        accent = Color(0xFF00E5FF),
        border = Color(0xFFFF3DF2).copy(alpha = 0.20f),
        isDark = true
    ),
    CodeForgeMobileTheme(
        id = "midnight-ocean",
        label = "Midnight Ocean",
        mood = "Dunkelblau",
        background = listOf(Color(0xFF071826), Color(0xFF06111B), Color(0xFF02080D)),
        sidebar = listOf(Color(0xFF0B2A3F), Color(0xFF02080D)),
        surface = Color(0xFF0B2234),
        surfaceStrong = Color(0xFF123348),
        text = Color(0xFFCFFAFE),
        mutedText = Color(0xFF8BB5C4),
        accent = Color(0xFF67E8F9),
        border = Color(0xFF67E8F9).copy(alpha = 0.16f),
        isDark = true
    ),
    CodeForgeMobileTheme(
        id = "forest-terminal",
        label = "Forest Terminal",
        mood = "Gruen und ruhig",
        background = listOf(Color(0xFF07130D), Color(0xFF0A1F14), Color(0xFF030704)),
        sidebar = listOf(Color(0xFF143322), Color(0xFF030704)),
        surface = Color(0xFF0E1B13),
        surfaceStrong = Color(0xFF172D20),
        text = Color(0xFFD1FAE5),
        mutedText = Color(0xFF8BBDA3),
        accent = Color(0xFF7DDC9F),
        border = Color(0xFF7DDC9F).copy(alpha = 0.16f),
        isDark = true
    ),
    CodeForgeMobileTheme(
        id = "solarized-dawn",
        label = "Solarized Dawn",
        mood = "Sanfter Morgen",
        background = listOf(Color(0xFFFDF6E3), Color(0xFFEEE8D5), Color(0xFFD6CEB2)),
        sidebar = listOf(Color(0xFFF8F0D6), Color(0xFFE1D6B8)),
        surface = Color(0xF2FFF8E6),
        surfaceStrong = Color(0xFFEEE8D5),
        text = Color(0xFF29323A),
        mutedText = Color(0xFF657B83),
        accent = Color(0xFF268BD2),
        border = Color.Black.copy(alpha = 0.10f),
        isDark = false
    ),
    CodeForgeMobileTheme(
        id = "rose-quartz",
        label = "Rose Quartz",
        mood = "Hell, warm, freundlich",
        background = listOf(Color(0xFFFFF1F2), Color(0xFFFCE7F3), Color(0xFFFBCFE8)),
        sidebar = listOf(Color(0xFFFFF1F2), Color(0xFFFBCFE8)),
        surface = Color(0xF2FFFFFF),
        surfaceStrong = Color(0xFFFFE4EE),
        text = Color(0xFF4A1022),
        mutedText = Color(0xFF9F4561),
        accent = Color(0xFFBE185D),
        border = Color(0xFFBE185D).copy(alpha = 0.14f),
        isDark = false
    ),
    CodeForgeMobileTheme(
        id = "mono-slate",
        label = "Mono Slate",
        mood = "Neutral und dicht",
        background = listOf(Color(0xFF0F172A), Color(0xFF111827), Color(0xFF020617)),
        sidebar = listOf(Color(0xFF1E293B), Color(0xFF020617)),
        surface = Color(0xFF111827),
        surfaceStrong = Color(0xFF1E293B),
        text = Color(0xFFE2E8F0),
        mutedText = Color(0xFF94A3B8),
        accent = Color(0xFFCBD5E1),
        border = Color.White.copy(alpha = 0.10f),
        isDark = true
    ),
    CodeForgeMobileTheme(
        id = "amber-console",
        label = "Amber Console",
        mood = "Terminal-Waerme",
        background = listOf(Color(0xFF160F06), Color(0xFF241505), Color(0xFF050301)),
        sidebar = listOf(Color(0xFF3B2608), Color(0xFF050301)),
        surface = Color(0xFF1F1306),
        surfaceStrong = Color(0xFF332006),
        text = Color(0xFFFFF1C2),
        mutedText = Color(0xFFC49B57),
        accent = Color(0xFFF59E0B),
        border = Color(0xFFF59E0B).copy(alpha = 0.18f),
        isDark = true
    ),
    CodeForgeMobileTheme(
        id = "arctic-blue",
        label = "Arctic Blue",
        mood = "Klar und hell",
        background = listOf(Color(0xFFEFF6FF), Color(0xFFDBEAFE), Color(0xFFBFDBFE)),
        sidebar = listOf(Color(0xFFF8FBFF), Color(0xFFD7E8FF)),
        surface = Color(0xF2FFFFFF),
        surfaceStrong = Color(0xFFE0EEFF),
        text = Color(0xFF172033),
        mutedText = Color(0xFF475569),
        accent = Color(0xFF2563EB),
        border = Color.Black.copy(alpha = 0.09f),
        isDark = false
    ),
    CodeForgeMobileTheme(
        id = "violet-noir",
        label = "Violet Noir",
        mood = "Elegant dunkel",
        background = listOf(Color(0xFF10051B), Color(0xFF1B0B2D), Color(0xFF05010A)),
        sidebar = listOf(Color(0xFF24113F), Color(0xFF05010A)),
        surface = Color(0xFF190B28),
        surfaceStrong = Color(0xFF281240),
        text = Color(0xFFF3E8FF),
        mutedText = Color(0xFFC7A6E3),
        accent = Color(0xFFC084FC),
        border = Color(0xFFC084FC).copy(alpha = 0.18f),
        isDark = true
    ),
    CodeForgeMobileTheme(
        id = "high-contrast",
        label = "High Contrast",
        mood = "Maximal lesbar",
        background = listOf(Color.Black, Color.Black, Color.Black),
        sidebar = listOf(Color.Black, Color.Black),
        surface = Color(0xFF050505),
        surfaceStrong = Color(0xFF111111),
        text = Color.White,
        mutedText = Color(0xFFD4D4D8),
        accent = Color(0xFF22C55E),
        border = Color.White,
        isDark = true
    ),
    CodeForgeMobileTheme(
        id = "aurora-flow",
        label = "Aurora Flow",
        mood = "Animierter Verlauf",
        background = listOf(Color(0xFF031716), Color(0xFF064E3B), Color(0xFF111827), Color(0xFF052E2B)),
        sidebar = listOf(Color(0xFF064E3B), Color(0xFF052E2B)),
        surface = Color(0xFF0B2421),
        surfaceStrong = Color(0xFF123B35),
        text = Color(0xFFECFDF5),
        mutedText = Color(0xFFA7F3D0),
        accent = Color(0xFFA7F3D0),
        border = Color(0xFFA7F3D0).copy(alpha = 0.18f),
        isDark = true
    ),
    CodeForgeMobileTheme(
        id = "neon-flow",
        label = "Neon Flow",
        mood = "Animierter Verlauf",
        background = listOf(Color(0xFF050505), Color(0xFF181026), Color(0xFF111827), Color(0xFF26123A)),
        sidebar = listOf(Color(0xFF181026), Color(0xFF26123A)),
        surface = Color(0xFF17111F),
        surfaceStrong = Color(0xFF261A35),
        text = Color(0xFFFAE8FF),
        mutedText = Color(0xFFE0B7F0),
        accent = Color(0xFF22D3EE),
        border = Color(0xFFEC4899).copy(alpha = 0.18f),
        isDark = true
    ),
    CodeForgeMobileTheme(
        id = "glass-apple-dark",
        label = "Apple Glass (Dunkel)",
        mood = "Mac-Stil Milchglas Dunkel",
        background = listOf(Color(0xFF0F0717), Color(0xFF070B19), Color(0xFF020205)),
        sidebar = listOf(Color(0xFF191923), Color(0xFF020205)),
        surface = Color(0xFF191428),
        surfaceStrong = Color(0xFF272039),
        text = Color(0xFFE4E4E7),
        mutedText = Color(0xFFA1A1AA),
        accent = Color(0xFFA855F7),
        border = Color.White.copy(alpha = 0.12f),
        isDark = true
    ),
    CodeForgeMobileTheme(
        id = "glass-apple-light",
        label = "Apple Glass (Hell)",
        mood = "Mac-Stil Milchglas Hell",
        background = listOf(Color(0xFFF3F4F6), Color(0xFFFDF4FF), Color(0xFFECFEFF)),
        sidebar = listOf(Color(0xFFFFFFFF), Color(0xFFECFEFF)),
        surface = Color(0xF2FFFFFF),
        surfaceStrong = Color(0xFFF0F0FF),
        text = Color(0xFF18181B),
        mutedText = Color(0xFF52525B),
        accent = Color(0xFF0EA5E9),
        border = Color.Black.copy(alpha = 0.09f),
        isDark = false
    )
)

fun mobileThemeById(id: String): CodeForgeMobileTheme {
    return CodeForgeMobileThemes.firstOrNull { it.id == id } ?: CodeForgeMobileThemes.first()
}
